export const PROVIDER_REGISTRY = [
  {
    id: 'netflix',
    label: 'Netflix',
    short: 'N',
    source: 'tmdb',
    defaultEnabled: true,
    aliases: ['netflix'],
    description: 'Netflix-Inhalte und Netflix-Anbieterbutton anzeigen.',
    homeTitle: 'Beliebt auf Netflix',
    movieTitle: 'Filme auf Netflix',
    seriesTitle: 'Serien auf Netflix',
    searchUrl: (title) => `https://www.netflix.com/search?q=${encodeURIComponent(title)}`,
  },
  {
    id: 'prime',
    label: 'Prime Video',
    short: 'P',
    source: 'tmdb',
    defaultEnabled: true,
    aliases: ['amazonprimevideo', 'primevideo'],
    description: 'Prime-Video-Inhalte und Prime-Video-Anbieterbutton anzeigen.',
    homeTitle: 'Highlights bei Prime Video',
    movieTitle: 'Filme bei Prime Video',
    seriesTitle: 'Serien bei Prime Video',
    searchUrl: (title) => `https://www.primevideo.com/search/ref=atv_nb_sr?phrase=${encodeURIComponent(title)}`,
  },
  {
    id: 'disney',
    label: 'Disney+',
    short: 'D+',
    source: 'tmdb',
    defaultEnabled: true,
    aliases: ['disneyplus', 'disney'],
    description: 'Disney+-Inhalte und Disney+-Anbieterbutton anzeigen.',
    homeTitle: 'Entdecken auf Disney+',
    movieTitle: 'Filme auf Disney+',
    seriesTitle: 'Serien auf Disney+',
    searchUrl: () => 'https://www.disneyplus.com/de-de',
  },
  {
    id: 'youtube',
    label: 'YouTube',
    short: 'YT',
    source: 'tmdb',
    defaultEnabled: true,
    aliases: ['youtube'],
    description: 'YouTube-Inhalte und YouTube-Anbieterbutton anzeigen.',
    homeTitle: 'Gefragt auf YouTube',
    movieTitle: 'Filme auf YouTube',
    seriesTitle: 'Serien auf YouTube',
    searchUrl: (title) => `https://www.youtube.com/results?search_query=${encodeURIComponent(title)}`,
  },
  {
    id: 'joyn',
    label: 'Joyn',
    short: 'J',
    source: 'tmdb',
    aliases: ['joyn', 'joynplus'],
    description: 'Joyn- und Joyn-PLUS+-Inhalte berücksichtigen.',
    homeTitle: 'Entdecken auf Joyn',
    movieTitle: 'Filme auf Joyn',
    seriesTitle: 'Serien auf Joyn',
    searchUrl: () => 'https://www.joyn.de/',
  },
  {
    id: 'wow',
    label: 'WOW',
    short: 'WOW',
    source: 'tmdb',
    aliases: ['wow'],
    description: 'Filme und Serien aus dem WOW-Angebot berücksichtigen.',
    homeTitle: 'Highlights bei WOW',
    movieTitle: 'Filme bei WOW',
    seriesTitle: 'Serien bei WOW',
    searchUrl: () => 'https://www.wowtv.de/',
  },
  {
    id: 'appletv',
    label: 'Apple TV+',
    short: 'A+',
    source: 'tmdb',
    aliases: ['appletvplus', 'appletv'],
    description: 'Apple-TV+-Aboinhalte berücksichtigen.',
    homeTitle: 'Highlights auf Apple TV+',
    movieTitle: 'Filme auf Apple TV+',
    seriesTitle: 'Serien auf Apple TV+',
    searchUrl: (title) => `https://tv.apple.com/de/search?term=${encodeURIComponent(title)}`,
  },
  {
    id: 'paramount',
    label: 'Paramount+',
    short: 'P+',
    source: 'tmdb',
    aliases: ['paramountplus', 'paramount'],
    description: 'Paramount+-Filme und -Serien berücksichtigen.',
    homeTitle: 'Neu bei Paramount+',
    movieTitle: 'Filme auf Paramount+',
    seriesTitle: 'Serien auf Paramount+',
    searchUrl: (title) => `https://www.paramountplus.com/de/search/?query=${encodeURIComponent(title)}`,
  },
  {
    id: 'rtlplus',
    label: 'RTL+',
    short: 'RTL+',
    source: 'tmdb',
    aliases: ['rtlplus', 'rtl'],
    description: 'RTL+-Filme und -Serien berücksichtigen.',
    homeTitle: 'Highlights auf RTL+',
    movieTitle: 'Filme auf RTL+',
    seriesTitle: 'Serien auf RTL+',
    searchUrl: () => 'https://plus.rtl.de/suche',
  },
  {
    id: 'crunchyroll',
    label: 'Crunchyroll',
    short: 'CR',
    source: 'tmdb',
    aliases: ['crunchyroll'],
    description: 'Anime-Filme und -Serien von Crunchyroll berücksichtigen.',
    homeTitle: 'Beliebt auf Crunchyroll',
    movieTitle: 'Filme auf Crunchyroll',
    seriesTitle: 'Serien auf Crunchyroll',
    searchUrl: (title) => `https://www.crunchyroll.com/search?q=${encodeURIComponent(title)}`,
  },
  {
    id: 'pluto',
    label: 'Pluto TV',
    short: 'PL',
    source: 'tmdb',
    aliases: ['plutotv'],
    description: 'Kostenlose und werbefinanzierte Pluto-TV-Inhalte berücksichtigen.',
    homeTitle: 'Kostenlos auf Pluto TV',
    movieTitle: 'Filme auf Pluto TV',
    seriesTitle: 'Serien auf Pluto TV',
    searchUrl: () => 'https://pluto.tv/de/',
  },
  {
    id: 'ard',
    label: 'ARD Mediathek',
    short: 'ARD',
    source: 'tmdb',
    aliases: ['ardmediathek'],
    description: 'Filme und Serien aus der ARD Mediathek berücksichtigen.',
    homeTitle: 'Aus der ARD Mediathek',
    movieTitle: 'Filme in der ARD Mediathek',
    seriesTitle: 'Serien in der ARD Mediathek',
    searchUrl: () => 'https://www.ardmediathek.de/suche',
  },
  {
    id: 'zdf',
    label: 'ZDF',
    short: 'ZDF',
    source: 'tmdb',
    aliases: ['zdf'],
    description: 'Filme und Serien aus dem ZDF-Streamingangebot berücksichtigen.',
    homeTitle: 'Aus dem ZDF',
    movieTitle: 'Filme im ZDF',
    seriesTitle: 'Serien im ZDF',
    searchUrl: (title) => `https://www.zdf.de/suche?q=${encodeURIComponent(title)}`,
  },
  {
    id: 'arte',
    label: 'arte',
    short: 'ARTE',
    source: 'tmdb',
    aliases: ['arte'],
    description: 'Filme und Serien aus der arte Mediathek berücksichtigen.',
    homeTitle: 'Aus der arte Mediathek',
    movieTitle: 'Filme bei arte',
    seriesTitle: 'Serien bei arte',
    searchUrl: (title) => `https://www.arte.tv/de/search/?q=${encodeURIComponent(title)}`,
  },
  {
    id: 'netzkino',
    label: 'Netzkino',
    short: 'NK',
    source: 'tmdb',
    aliases: ['netzkino'],
    description: 'Kostenlose werbefinanzierte Filme von Netzkino berücksichtigen.',
    homeTitle: 'Kostenlos bei Netzkino',
    movieTitle: 'Filme bei Netzkino',
    seriesTitle: 'Serien bei Netzkino',
    searchUrl: () => 'https://www.netzkino.de/',
  },
  {
    id: 'magenta',
    label: 'MagentaTV+',
    short: 'M+',
    source: 'tmdb',
    aliases: ['magentatvplus', 'magentatv'],
    description: 'MagentaTV+-Inhalte berücksichtigen, sofern TMDB sie in Deutschland als Watch Provider liefert.',
    homeTitle: 'Highlights bei MagentaTV+',
    movieTitle: 'Filme bei MagentaTV+',
    seriesTitle: 'Serien bei MagentaTV+',
    searchUrl: () => 'https://web.magentatv.de/',
  },
  {
    id: 'waipu',
    label: 'waipu.tv',
    short: 'W',
    source: 'special',
    defaultEnabled: true,
    aliases: ['waiputv'],
    description: 'waipu.tv bleibt angebunden; der vollständige Waiputhek-Katalog folgt separat mit eigener Datenquelle.',
    searchUrl: () => 'https://app.waipu.tv/waiputhek',
  },
]

export const PROVIDER_BY_ID = Object.fromEntries(PROVIDER_REGISTRY.map((provider) => [provider.id, provider]))
export const TMDB_PROVIDER_REGISTRY = PROVIDER_REGISTRY.filter((provider) => provider.source === 'tmdb')
export const DEFAULT_ENABLED_PROVIDER_IDS = PROVIDER_REGISTRY
  .filter((provider) => provider.defaultEnabled)
  .map((provider) => provider.id)

export function providerFromTmdbName(value) {
  const normalized = String(value || '')
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]/gi, '')
    .toLowerCase()

  return TMDB_PROVIDER_REGISTRY.find((provider) => provider.aliases.includes(normalized)) || null
}
