import { FIELD_DECISIONS } from '../fieldDiscovery.js'

export const TMDB_WATCH_PROVIDER_FIELD_POLICY = Object.freeze({
  'results': { decision: FIELD_DECISIONS.CORE, reason: 'Regional watch-provider container.' },
  'results.DE': { decision: FIELD_DECISIONS.CORE, reason: 'Configured Movie Hub region.' },
  'results.DE.link': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'tmdb', reason: 'TMDB/JustWatch landing link; not a direct content deep link.' },
  'results.DE.flatrate': { decision: FIELD_DECISIONS.CAPABILITY, capability: 'availability', reason: 'Maps to flatrate availability.' },
  'results.DE.free': { decision: FIELD_DECISIONS.CAPABILITY, capability: 'availability', reason: 'Maps to free availability.' },
  'results.DE.ads': { decision: FIELD_DECISIONS.CAPABILITY, capability: 'availability', reason: 'Maps to ad-supported availability.' },
  'results.DE.rent': { decision: FIELD_DECISIONS.CAPABILITY, capability: 'availability', reason: 'Maps to rental availability.' },
  'results.DE.buy': { decision: FIELD_DECISIONS.CAPABILITY, capability: 'availability', reason: 'Maps to purchase availability.' },
  'results.DE.flatrate.provider_id': { decision: FIELD_DECISIONS.CORE },
  'results.DE.flatrate.provider_name': { decision: FIELD_DECISIONS.CORE },
  'results.DE.free.provider_id': { decision: FIELD_DECISIONS.CORE },
  'results.DE.free.provider_name': { decision: FIELD_DECISIONS.CORE },
  'results.DE.ads.provider_id': { decision: FIELD_DECISIONS.CORE },
  'results.DE.ads.provider_name': { decision: FIELD_DECISIONS.CORE },
  'results.DE.rent.provider_id': { decision: FIELD_DECISIONS.CORE },
  'results.DE.rent.provider_name': { decision: FIELD_DECISIONS.CORE },
  'results.DE.buy.provider_id': { decision: FIELD_DECISIONS.CORE },
  'results.DE.buy.provider_name': { decision: FIELD_DECISIONS.CORE },
  'results.DE.flatrate.logo_path': { decision: FIELD_DECISIONS.REJECT, reason: 'Movie Hub uses its own provider presentation; remote provider logos are not required here.' },
  'results.DE.free.logo_path': { decision: FIELD_DECISIONS.REJECT, reason: 'Movie Hub uses its own provider presentation.' },
  'results.DE.ads.logo_path': { decision: FIELD_DECISIONS.REJECT, reason: 'Movie Hub uses its own provider presentation.' },
  'results.DE.rent.logo_path': { decision: FIELD_DECISIONS.REJECT, reason: 'Movie Hub uses its own provider presentation.' },
  'results.DE.buy.logo_path': { decision: FIELD_DECISIONS.REJECT, reason: 'Movie Hub uses its own provider presentation.' },
  'results.DE.flatrate.display_priority': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'tmdb', reason: 'Retained as source ordering metadata; Movie Hub does not adopt it as a product sorting rule.' },
  'results.DE.free.display_priority': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'tmdb', reason: 'Retained as source ordering metadata; Movie Hub does not adopt it as a product sorting rule.' },
  'results.DE.ads.display_priority': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'tmdb', reason: 'Retained as source ordering metadata; Movie Hub does not adopt it as a product sorting rule.' },
  'results.DE.rent.display_priority': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'tmdb', reason: 'Retained as source ordering metadata; Movie Hub does not adopt it as a product sorting rule.' },
  'results.DE.buy.display_priority': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'tmdb', reason: 'Retained as source ordering metadata; Movie Hub does not adopt it as a product sorting rule.' },
})
