import { FIELD_DECISIONS } from '../fieldDiscovery.js'

export const WAIPU_SYNC_UPSTREAM_FIELD_POLICY = Object.freeze({
  '$schema': { decision: FIELD_DECISIONS.REJECT, reason: 'Technical schema metadata; no Movie Hub product value.' },
  'stations': { decision: FIELD_DECISIONS.CORE },
  'channels': { decision: FIELD_DECISIONS.CORE },
  'displayName': { decision: FIELD_DECISIONS.CORE },
  'name': { decision: FIELD_DECISIONS.CORE },
  'logoTemplateUrl': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'logoUrl': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'logo': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'streamQualities': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'qualities': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'channels.id': { decision: FIELD_DECISIONS.CORE },
  'channels.stationId': { decision: FIELD_DECISIONS.CORE },
  'channels.uuid': { decision: FIELD_DECISIONS.CORE },
  'channels.displayName': { decision: FIELD_DECISIONS.CORE },
  'channels.name': { decision: FIELD_DECISIONS.CORE },
  'channels.title': { decision: FIELD_DECISIONS.CORE },
  'channels.logoTemplateUrl': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'channels.logoUrl': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'channels.logo': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'channels.streamQualities': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'channels.qualities': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'stations.id': { decision: FIELD_DECISIONS.CORE },
  'stations.stationId': { decision: FIELD_DECISIONS.CORE },
  'stations.uuid': { decision: FIELD_DECISIONS.CORE },
  'stations.displayName': { decision: FIELD_DECISIONS.CORE },
  'stations.name': { decision: FIELD_DECISIONS.CORE },
  'stations.title': { decision: FIELD_DECISIONS.CORE },
  'stations.logoTemplateUrl': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'stations.logoUrl': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'stations.logo': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'stations.streamQualities': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'stations.qualities': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'slots': { decision: FIELD_DECISIONS.CORE },
  'timeSlots': { decision: FIELD_DECISIONS.CORE },
  'slotDurationHours': { decision: FIELD_DECISIONS.CORE },
  'slotSizeHours': { decision: FIELD_DECISIONS.CORE },
  'timezone': { decision: FIELD_DECISIONS.CORE },
  'id': { decision: FIELD_DECISIONS.CORE },
  'programId': { decision: FIELD_DECISIONS.CORE },
  'uuid': { decision: FIELD_DECISIONS.CORE },
  'title': { decision: FIELD_DECISIONS.CORE },
  'textContent': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'textContent.title': { decision: FIELD_DECISIONS.CORE },
  'startTime': { decision: FIELD_DECISIONS.CORE },
  'start': { decision: FIELD_DECISIONS.CORE },
  'stopTime': { decision: FIELD_DECISIONS.CORE },
  'stop': { decision: FIELD_DECISIONS.CORE },
  'endTime': { decision: FIELD_DECISIONS.CORE },
  'episodeTitle': { decision: FIELD_DECISIONS.CORE },
  'genre': { decision: FIELD_DECISIONS.CORE },
  'mainGenre': { decision: FIELD_DECISIONS.CORE },
  'category': { decision: FIELD_DECISIONS.CORE },
  'seriesId': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'imageUrl': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'previewImageUrl': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'previewImage': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu', reason: 'Source artwork fallback; TMDB remains canonical artwork source.' },
  'recordingForbidden': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu', reason: 'Source-specific recording restriction; candidate for later recording capability.' },
  'trackingContentId': { decision: FIELD_DECISIONS.REVIEW, reason: 'Needs product/technical decision: source identity value versus analytics-only tracking metadata.' },
})

export const WAIPU_PROGRAM_UPSTREAM_FIELD_POLICY = Object.freeze({
  '$schema': { decision: FIELD_DECISIONS.REJECT, reason: 'Technical schema metadata; no Movie Hub product value.' },
  'id': { decision: FIELD_DECISIONS.CORE },
  'programId': { decision: FIELD_DECISIONS.CORE },
  'uuid': { decision: FIELD_DECISIONS.CORE },
  'title': { decision: FIELD_DECISIONS.CORE },
  'originalTitle': { decision: FIELD_DECISIONS.CORE },
  'description': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'shortDescription': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'textContent': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'textContent.title': { decision: FIELD_DECISIONS.CORE },
  'textContent.titleOriginal': { decision: FIELD_DECISIONS.CORE },
  'textContent.originalTitle': { decision: FIELD_DECISIONS.CORE },
  'textContent.descLong': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'textContent.description': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'textContent.descShort': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'production': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'production.year': { decision: FIELD_DECISIONS.CORE },
  'production.countries': { decision: FIELD_DECISIONS.CORE },
  'productionYear': { decision: FIELD_DECISIONS.CORE },
  'productionCountries': { decision: FIELD_DECISIONS.CORE },
  'contentMeta': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'contentMeta.mainGenre': { decision: FIELD_DECISIONS.CORE },
  'contentMeta.subGenres': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'contentMeta.ageRating': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'mainGenre': { decision: FIELD_DECISIONS.CORE },
  'genre': { decision: FIELD_DECISIONS.CORE },
  'subGenres': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'series': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'series.id': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'series.seasonNumber': { decision: FIELD_DECISIONS.CORE },
  'series.episodeNumber': { decision: FIELD_DECISIONS.CORE },
  'series.episodeTitle': { decision: FIELD_DECISIONS.CORE },
  'seriesId': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'seasonNumber': { decision: FIELD_DECISIONS.CORE },
  'episodeNumber': { decision: FIELD_DECISIONS.CORE },
  'episodeTitle': { decision: FIELD_DECISIONS.CORE },
  'ageRating': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'imageUrls': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'recordingRestrictions': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'playbackRestrictions': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu' },
  'restrictions': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu', reason: 'Source playback/recording restrictions; retain losslessly until stable capabilities are derived.' },
  'rerun': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu', reason: 'Potential product value for broadcast context; source-specific for V1.' },
  'newTvMeta': { decision: FIELD_DECISIONS.EXTENSION, extensionNamespace: 'waipu', reason: 'Contains source content identity/publication-window data with possible later product value.' },
  'startTime': { decision: FIELD_DECISIONS.CORE, reason: 'Broadcast correlation/time identity.' },
  'stopTime': { decision: FIELD_DECISIONS.CORE, reason: 'Broadcast correlation/time identity.' },
  'stationId': { decision: FIELD_DECISIONS.CORE, reason: 'Broadcast channel identity.' },
  'trackingContentId': { decision: FIELD_DECISIONS.REVIEW, reason: 'Needs product/technical decision: source identity value versus analytics-only tracking metadata.' },
})
